export const resources = [
  { id: "a", title: "Auditorium A" },
  { id: "b", title: "Auditorium B", eventColor: "green" },
  { id: "c", title: "Auditorium C", eventColor: "orange" },
  {
    id: "d",
    title: "Auditorium D",
    children: [
      { id: "d1", title: "Room D1" },
      { id: "d2", title: "Room D2" },
      { id: "g", title: "Auditorium G" },
      { id: "h", title: "Auditorium H" },
      { id: "i", title: "Auditorium I" },
      { id: "j", title: "Auditorium J" },
      { id: "k", title: "Auditorium K" },
      { id: "l", title: "Auditorium L" },
      { id: "m", title: "Auditorium M" },
    ],
  },
  {
    id: "e",
    title: "Auditorium E",
    children: [
      { id: "n", title: "Auditorium N" },
      { id: "o", title: "Auditorium O" },
      { id: "p", title: "Auditorium P" },
      { id: "q", title: "Auditorium Q" },
      { id: "r", title: "Auditorium R" },
      { id: "s", title: "Auditorium S" },
      { id: "t", title: "Auditorium T" },
      { id: "u", title: "Auditorium U" },
      { id: "v", title: "Auditorium V" },
      { id: "w", title: "Auditorium W" },
      { id: "x", title: "Auditorium X" },
    ],
  },
  { id: "f", title: "Auditorium F", eventColor: "red" },

  { id: "y", title: "Auditorium Y" },
  { id: "z", title: "Auditorium Z" },
];
